general.import = ["~/.config/alacritty/base16-default-dark.toml"]

[font]
size = 16.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[terminal.shell]
program = "fish"

[env]
TERM = "xterm-256color"
