general.import = ["/home/leonardocee/.config/alacritty/base16-default-dark.toml"]

[font]
size = 14.0

[font.normal]
family = "FiraCodeNerdFont"
style = "SemiBold"

[terminal.shell]
program = "fish"

#[window]
#decorations = "none"

[env]
TERM = "xterm-256color"
